# Generated by Django 3.2.6 on 2023-11-17 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=3)),
                ('Amount', models.DecimalField(decimal_places=0, max_digits=5)),
                ('donnees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.banque')),
            ],
        ),
    ]
